### ISSUE TITLE
Macros - feature request

### ISSUE THREAD

**Issue by hermanekt** [gr8b/zabbix-module-experiments#1]
Hi Gregory,

this is excelent example for popup modul. Can be extended URL A, B, C, section via macros?
Exampe macros: {HOST.IP}, {HOST.ID}, {HOST.NAME}, {HOST.ALIAS} , {HOST.CONN},  {HOST.NAME}

Example URL A in inventory:
https://{HOST.NAME}/idrac

BTW i test your module on versions:
6.0.0alpha7
5.0.5 LTS

Thank you,
Tom

**Comment by gr8b** [comment]
Thank you for support. :) I added simple example of resolving host macro in url field.

**Comment by hermanekt** [comment]
Hi, it is working perfectly!
